import { stopChildren } from './security/children.js';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import http from 'node:http';
import { config } from './config.js';
import { localTransport, disabled } from './security/transport.js';
import { authenticate } from './middleware/auth.js';
import { apiLimiter } from './middleware/rateLimiter.js';
import { initializeDatabase, closeDatabase } from './utils/database.js';
import { ensureDataDirectories } from './utils/fileSystem.js';
import authRoutes from './routes/authRoutes.js';
import chatRoutes from './routes/chat.js';
import toolsRoutes from './routes/tools.js';
import filesRoutes from './routes/files.js';
import appsRoutes from './routes/apps.js';
import tasksRoutes from './routes/tasks.js';
import memoryRoutes from './routes/structuredMemory.js';
import profileRoutes from './routes/profile.js';
import ttsRoutes from './routes/tts.js';
import voiceRoutes from './routes/voice.js';
const settings = config();
export const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: ['null','http://localhost:5173','http://127.0.0.1:5173'], allowedHeaders: ['Content-Type','Authorization','X-Vezora-Token'] }));
app.use(localTransport(settings.token));
app.use(express.json({ limit: '1mb' }));
app.get('/health', (_req,res) => res.json({ status: 'ready' }));
app.use('/api', apiLimiter);
app.use('/api/auth', authRoutes);
app.use('/api', authenticate);
// These legacy paths lack safe ownership, bounded input, or confirmation semantics.
for (const route of ['gmail','calendar','workflows','ocr','memory','logs','settings','search','coordinator']) app.use('/api/' + route, disabled);
app.use('/auth', disabled);
app.use('/api/chat/stream', disabled);
app.use('/api/chat/intent', disabled);
app.use('/api/chat', chatRoutes);
app.use('/api/tools', toolsRoutes);
app.use('/api/files', filesRoutes);
app.use('/api/apps', appsRoutes);
app.use('/api/tasks', tasksRoutes);
app.use('/api/structured-memory', memoryRoutes);
app.use('/api/profile', profileRoutes);
app.use('/api/tts', ttsRoutes);
app.use('/api/voice', voiceRoutes);
app.use((_req,res) => res.status(404).json({ error: 'Not found' }));
app.use((error,_req,res,_next) => {
  if (!res.headersSent) res.status(error.status || 500).json({ error: 'Request failed' });
});
const server = http.createServer(app);
server.on('upgrade',(_req,socket) => socket.destroy()); // Unimplemented voice WS is not exposed.
server.requestTimeout = 30000;
server.headersTimeout = 10000;
let shuttingDown = false;
function shutdown() {
  if (shuttingDown) return;
  shuttingDown = true;
  stopChildren();
  server.close(() => { closeDatabase(); process.exit(0); });
  server.closeIdleConnections();
  setTimeout(() => process.exit(1),3000).unref();
}
process.on('SIGTERM',shutdown);
process.on('SIGINT',shutdown);
process.on('disconnect',shutdown);
process.on('message',message => { if (message?.type === 'shutdown') shutdown(); });
process.parentPort?.on('message',event => { if (event.data?.type === 'shutdown') shutdown(); });
await ensureDataDirectories();
await initializeDatabase();
server.on('error',() => { console.error('Backend failed to bind'); process.exit(1); });
server.listen(settings.port, settings.host, () => {
  const ready = { type: 'ready', port: server.address().port };
  process.parentPort?.postMessage(ready);
  process.send?.(ready);
  console.log('Local backend ready');
});
