import fs from 'node:fs/promises';
import path from 'node:path';
import { backendSource, privateArtifact } from './package-policy.mjs';
const root=path.resolve('.package/backend');
// Stage a fresh directory; refuse stale files rather than deleting a user directory.
if (path.dirname(root) !== path.resolve('.package') || path.basename(root) !== 'backend') throw new Error('Invalid staging target');
try {
  const stat=await fs.lstat(root);
  if (stat.isSymbolicLink()) throw new Error('Linked staging target refused');
  await fs.access(path.join(root,'.vezora-generated'));
  await fs.rm(root,{recursive:true,force:true});
} catch(error) { if(error.code!=='ENOENT') throw error; }
await fs.mkdir(root,{recursive:true});
await fs.writeFile(path.join(root,'.vezora-generated'),'Generated by Vezora package staging.');
async function copy(dir,relative='') {
  for(const entry of await fs.readdir(dir,{withFileTypes:true})) {
    const rel=relative ? relative+'/'+entry.name : entry.name;
    if(entry.isSymbolicLink() || privateArtifact(rel) || entry.name==='.bin') continue;
    const dependency=rel==='node_modules' || rel.startsWith('node_modules/');
    if(entry.isDirectory()) {
      if(dependency || !relative && ['controllers','core','middleware','models','routes','services','utils','security'].includes(entry.name)) await copy(path.join(dir,entry.name),rel);
    } else if(dependency || backendSource(rel)) {
      await fs.mkdir(path.dirname(path.join(root,rel)),{recursive:true});
      await fs.copyFile(path.join(dir,entry.name),path.join(root,rel));
    }
  }
}
await copy(path.resolve('backend'));
console.log('Staged allowlisted backend source and restored dependencies; no runtime data or .env copied.');
